### PR TITLE
CPP-3444 Update bitbucket-pipelines.yml

### PR DESCRIPTION
**Pull request by wouter-admiraal-sonarsource**
This fixes the pipelines, as reported by https://jira.sonarsource.com/browse/SONAR-15833

### CODE REVIEW

**Comment by wouter-admiraal-sonarsource** [comment]
@amelie-renard-sonarsource Can I ask you for a review on this 🙏 ?

**Comment by arseniy-sonar** [comment]
@wouter-admiraal-sonarsource , could you, please, also fix the reference to `sonarqube-scan` in the [README](sonarqube-scan)? You can use the [README for SonarCloud](https://github.com/sonarsource-cfamily-examples/linux-autotools-bitbucket-sc/blob/main/README.adoc) as a source of inspiration

**Review by arseniy-sonar — CHANGES_REQUESTED** [review]
@wouter-admiraal-sonarsource , could you, please, also fix the reference to `sonarqube-scan` in the [README](https://github.com/sonarsource-cfamily-examples/linux-autotools-bitbucket-sq/blob/main/README.adoc)? You can use the [README for SonarCloud](https://github.com/sonarsource-cfamily-examples/linux-autotools-bitbucket-sc/blob/main/README.adoc) as a source of inspiration

**Comment by wouter-admiraal-sonarsource** [comment]
Good catch @arseniy-sonar 👍 . I've updated the commit.

**Review by arseniy-sonar — APPROVED** [review]

**Pull request merged**
